### ISSUE TITLE
Undefined as a special object

### ISSUE THREAD

**Issue by patarapolw** [ltworf/typedload#86] opened 2019-06-28 09:10 UTC
So that NamedTuple when converted to `dict` would have "no key" instead of `None`.

Perhaps, `Optional[]` will do?

**Comment by ltworf** [comment] 2019-06-28 10:49
I do not understand what the problem is. Can you post a minimal code example of what it does and what you'd want it to do?

**Comment by patarapolw** [comment] 2019-06-29 04:48
```python
class IEntry(NamedTuple):
    front: str = ""
    deck: str = ""
    id: Optional[int] = None
    back: Optional[str] = None
    mnemonic: Optional[str] = None
    tag: Optional[List[str]] = None
    srsLevel: Optional[int]  = None
    nextReview: Optional[str] = None
    created: Optional[str] = None
    modified: Optional[str] = None
    stat: Optional[IStat] = None
    template: Optional[str] = None
    model: Optional[str] = None
    tFront: Optional[str] = None
    tBack: Optional[str] = None
    css: Optional[str] = None
    js: Optional[str] = None
    key: Optional[str] = None
    data: Optional[List[IDataSocket]] = None
    source: Optional[str] = None
    sH: Optional[str] = None
    sCreated: Optional[str] = None

print(typedload.dump(IEntry())
```

Should preferably yield

```
{"front":"", "deck": ""}
```

**Comment by ltworf** [comment] 2019-06-29 09:10
It just hides the fields which have the same value as the default value, so `None` is in no way different than `''` or whatever other arbitrary value you might chose.

You can implement custom behaviours by adding specific handlers.

Closing this.

**Closed by ltworf** 2019-06-29 09:10 UTC
